apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ..\..\apps\kompose-windows-amd64.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-server
  name: flask-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ..\..\apps\kompose-windows-amd64.exe convert
        kompose.version: 1.24.0 (7c629530)
      creationTimestamp: null
      labels:
        io.kompose.service: flask-server
    spec:
      containers:
        - env:
            - name: FLASK_HOST
              value: 0.0.0.0
            - name: FLASK_PORT
              value: "5000"
          image: flask-server
          name: flask-server
          ports:
            - containerPort: 5000
          resources: {}
      hostname: flask-server
      restartPolicy: Always
status: {}
