apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ..\..\apps\kompose-windows-amd64.exe convert
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-server
  name: flask-server
spec:
  ports:
    - name: "5050"
      port: 5050
      targetPort: 5000
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: flask-server
  type: NodePort
